### ISSUE TITLE
What's the usage of the code I memtioned ?

### ISSUE THREAD

**Issue by SgtDaJim** [pixelbender/go-traceroute#1]
https://github.com/pixelbender/go-traceroute/blob/ad1b2298e975e4133f3663be72a3e892a4a5508d/traceroute/tracer.go#L110-L120
Hi @pixelbender , I am curious about the usage of the code I memtioned. That codes look like it just does nothing and makes the function end after `deadline`.

**Comment by pixelbender** [comment]
It keeps handling responses until context is cancelled (it may be external canceling) or deadline reached.

**Comment by SgtDaJim** [comment]
https://github.com/pixelbender/go-traceroute/blob/ad1b2298e975e4133f3663be72a3e892a4a5508d/traceroute/tracer.go#L86-L108
But in this loop, when ttl reach max or last IP == test IP, the loop will break, and sess.Probe(ttl) will not execute any more, so there will not any responces come in, right?

**Comment by pixelbender** [comment]
Yes this loop breaks if max TTL or target IP is reached but delay*maxTTL is generally smaller than timeout, so we should wait upcoming responses here.

**Comment by pixelbender** [comment]
Note that sess.Probe just sends a single packet and does not wait any response.

**Comment by pixelbender** [comment]
In fact, the code can be optimized, so we can exit if all hops responsed before deadline. Thank you )

**Comment by SgtDaJim** [comment]
How about that, generate the sess.C every loop, when time reach Delay, set sess.C = nil. 
when getting a response, check whether the sess.C is nil, if not, send the response into sess.C

**Comment by SgtDaJim** [comment]
wait, dose the Delay mean timeout and abandon the response or consider the packet loss?

**Comment by pixelbender** [comment]
Nope, delay is a time between probes, ignored when response comes, not timeout.

**Comment by pixelbender** [comment]
Fixed last wait loop, now it exits faster

**Comment by SgtDaJim** [comment]
er, ok, i will read and try the new version tomorrow.
but i think the t.conn shoud set a timeout too.
like t.conn.setDeadline(timeout)

**Comment by pixelbender** [comment]
What exactly makes this implementation different from others: It can make thousands of simultaneous traceroutes using the same Tracer (and single network socket). So it should handle timeouts separately.

**Comment by SgtDaJim** [comment]
understood. Actually i am creating a go-base MTR implementing your traceroute program. So except traceroute, I need Ping. So I might need the additional timeout then.

**Comment by pixelbender** [comment]
Ok, you can make iterative traces like this:
```go
ip := net.ParseIP("1.1.1.1")
deadline := time.Now().Add(10*time.Second)
ctx := context.Background()

handle := func(r *traceroute.Reply) {
	log.Println(r.Hops, r.IP, r.RTT)
}
tracer := &traceroute.Tracer{
	Config: traceroute.DefaultConfig,
}
tracer.Count = 1
for time.Now().Before(deadline) {
	err := tracer.Trace(ctx, ip, handle)
	if err != nil {
		log.Println(err)
	}
	time.Sleep(tracer.Delay)
}
```

**Comment by pixelbender** [comment]
Just added TestPing. Note that reply.Hops always zero for Ping
